[project]
name = "mtg-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "tqdm>=4.67.1",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["mtg_ai*"]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
